drop table if EXISTS auth;
drop table if EXISTS botdata;
drop table if exists groupdata;
INSERT INTO auth (
    noicekeyprvt,
    noicekeypub,
    signedidentitykeyprvt,
    signedidentitykeypub,
    signedprekeypairprv,
    signedprekeypairpub,
    signedprekeysignature,
    signedprekeyidb,
    registrationidb,
    advsecretkeyb,
    nextprekeyidb,
    firstunuploadedprekeyidb,
    serverhasprekeysb,
    accountdetailsb,
    accountsignaturekeyb,
    accountsignatureb,
    devicesignatureb,
    meidb,
    meverifiednameb,
    menameb,
    signalidentitiesnameb,
    signalidentitiesdeviceidb,
    signalidentitieskey,
    lastaccountsynctimestampb,
    myappstatekeyidb
  )
VALUES (
    'noicekeyprvt:text',
    'noicekeypub:text',
    'signedidentitykeyprvt:text',
    'signedidentitykeypub:text',
    'signedprekeypairprv:text',
    'signedprekeypairpub:text',
    'signedprekeysignature:text',
    'signedprekeyidb:text',
    'registrationidb:text',
    'advsecretkeyb:text',
    'nextprekeyidb:text',
    'firstunuploadedprekeyidb:text',
    'serverhasprekeysb:text',
    'accountdetailsb:text',
    'accountsignaturekeyb:text',
    'accountsignatureb:text',
    'devicesignatureb:text',
    'meidb:text',
    'meverifiednameb:text',
    'menameb:text',
    'signalidentitiesnameb:text',
    'signalidentitiesdeviceidb:text',
    'signalidentitieskey:text',
    'lastaccountsynctimestampb:text',
    'myappstatekeyidb:text'
  );
SELECT * FROM botdata;